### ISSUE TITLE
turn robots off

### ISSUE THREAD

**Issue by wpreimes** [cpaulik/datedown#5]
Hey! I'm trying to recursively download[ SMAP L3 data ](https://n5eil01u.ecs.nsidc.org/SMAP/SPL3SMP.005/)using `datedown` It seems like recursive download only works when turning off "robots" in `wget`. Is there some way in datedown for this (or for passing this to wget)? If not would you mind if we added it to [`download`](https://github.com/cpaulik/datedown/blob/bdf249b18dcd48826a0eedc7d9b7affae5eabc56/datedown/down.py#L41) (also [`wget.download`](https://github.com/cpaulik/datedown/blob/bdf249b18dcd48826a0eedc7d9b7affae5eabc56/datedown/wget.py#L31) [`wget.map_download`](https://github.com/cpaulik/datedown/blob/bdf249b18dcd48826a0eedc7d9b7affae5eabc56/datedown/wget.py#L88) I guess)?
See also TUW-GEO/smap_io#10

**Comment by cpaulik** [comment]
Feel free to add the option.

**Comment by wpreimes** [comment]
I have added the option in the smap package only for now, if we need it more frequently, I will add it here.
